version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DJANGO_DEBUG=1
      - DJANGO_SECRET="THIS_IS_NOT_SECRET_DO_NOT_USE_IN_PRODUCTION"
